name: Actualizar gráfica de commits

on:
  schedule:
    - cron: '0 0 * * *'  # Corre todos los días a la medianoche

jobs:
  update-graph:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install matplotlib requests

    - name: Run script
      run: python script.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'FrankQu29'
        git config --global user.email 'tepoxfrancisco1@gmail.com'
        git add commits.png
        git commit -m 'Actualizar gráfica de commits'
        git push
      with:
        username: ${{ secrets.USER_NAM }}
        password: ${{ secrets.USER_TOK }}


